### ISSUE TITLE
Unfortunate typo

### ISSUE THREAD

**Issue by barrypress** [quells/Squall#6]
There's an unfortunate typo in Mersenne:88 - the shift count should be l (letter L), not the number 1.

**Comment by quells** [comment]
Thanks very much! Merged a fix.

**Comment by barrypress** [comment]
I saw it. NP. 

I’d have built a pull request, but (shamefully) I’ve never needed to learn how, and right now isn’t a good time to dope it out. My git skills are virtually nonexistent.

Thanks for a nice bit of code!

Barry

---
"They laughed at Columbus, they laughed at Fulton, they laughed at the Wright Brothers. But they also laughed at Bozo the Clown." - Carl Sagan

**Comment by barrypress** [comment]
May I bug you, please?

It seems that if I seed the 32-bit generator with 7974, the addition of discardMultiply() + I overflows. Should it be a non-overflowing addition?

Thanks

Barry

---
"They laughed at Columbus, they laughed at Fulton, they laughed at the Wright Brothers. But they also laughed at Bozo the Clown." - Carl Sagan

**Comment by quells** [comment]
Huh. I've never had that happen to me with a random seed (although I've probably initialized fewer than 1000 instances so I haven't exactly explored the search space). I also found and fixed another potential overflow: https://github.com/quells/Squall/pull/8

Thanks again!
